#!/usr/bin/env bash
set -ex

export DANDI_API_KEY=$API_SECRET

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u run_capsule.py "$@"

